//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodBranch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienDongGia
    {
        public string ID { get; set; }
        public string IDMonAn { get; set; }
        public Nullable<double> GiaApDung { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<bool> Lock { get; set; }
    
        public virtual MonAn MonAn { get; set; }
    }
}
