//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodBranch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyFastFoodEntities1 : DbContext
    {
        public QuanLyFastFoodEntities1()
            : base("name=QuanLyFastFoodEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangTin> BangTins { get; set; }
        public virtual DbSet<BienDongGia> BienDongGias { get; set; }
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<ChiTietCT> ChiTietCTs { get; set; }
        public virtual DbSet<ChiTietHD> ChiTietHDs { get; set; }
        public virtual DbSet<ChiTietKho> ChiTietKhoes { get; set; }
        public virtual DbSet<ChiTietPNX> ChiTietPNXes { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CongThuc> CongThucs { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<LoaiKH> LoaiKHs { get; set; }
        public virtual DbSet<MonAn> MonAns { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieux { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuNhapXuat> PhieuNhapXuats { get; set; }
        public virtual DbSet<MonAnChiNhanh> MonAnChiNhanhs { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<DSYT> DSYTs { get; set; }
    
        public virtual ObjectResult<Nullable<System.DateTime>> sp_ChinhSuaBDG(string id, string idmonan, Nullable<double> giaApdung, Nullable<System.DateTime> ngayapdung, Nullable<System.DateTime> ngayhethan)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var idmonanParameter = idmonan != null ?
                new ObjectParameter("idmonan", idmonan) :
                new ObjectParameter("idmonan", typeof(string));
    
            var giaApdungParameter = giaApdung.HasValue ?
                new ObjectParameter("giaApdung", giaApdung) :
                new ObjectParameter("giaApdung", typeof(double));
    
            var ngayapdungParameter = ngayapdung.HasValue ?
                new ObjectParameter("ngayapdung", ngayapdung) :
                new ObjectParameter("ngayapdung", typeof(System.DateTime));
    
            var ngayhethanParameter = ngayhethan.HasValue ?
                new ObjectParameter("ngayhethan", ngayhethan) :
                new ObjectParameter("ngayhethan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("sp_ChinhSuaBDG", idParameter, idmonanParameter, giaApdungParameter, ngayapdungParameter, ngayhethanParameter);
        }
    
        public virtual int sp_ChinhSuaCN(string id, string tencn, string diachi, string nvql)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var tencnParameter = tencn != null ?
                new ObjectParameter("tencn", tencn) :
                new ObjectParameter("tencn", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var nvqlParameter = nvql != null ?
                new ObjectParameter("nvql", nvql) :
                new ObjectParameter("nvql", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaCN", idParameter, tencnParameter, diachiParameter, nvqlParameter);
        }
    
        public virtual int sp_ChinhSuaCT(string idct, string tenct, string mota)
        {
            var idctParameter = idct != null ?
                new ObjectParameter("idct", idct) :
                new ObjectParameter("idct", typeof(string));
    
            var tenctParameter = tenct != null ?
                new ObjectParameter("tenct", tenct) :
                new ObjectParameter("tenct", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaCT", idctParameter, tenctParameter, motaParameter);
        }
    
        public virtual int sp_ChinhSuaCTCT(string id, string idnguyenlieu, string idcongthuc, Nullable<int> soluong)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var idnguyenlieuParameter = idnguyenlieu != null ?
                new ObjectParameter("idnguyenlieu", idnguyenlieu) :
                new ObjectParameter("idnguyenlieu", typeof(string));
    
            var idcongthucParameter = idcongthuc != null ?
                new ObjectParameter("idcongthuc", idcongthuc) :
                new ObjectParameter("idcongthuc", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaCTCT", idParameter, idnguyenlieuParameter, idcongthucParameter, soluongParameter);
        }
    
        public virtual int sp_ChinhSuaDanhMuc(string iddm, string tendanhmuc)
        {
            var iddmParameter = iddm != null ?
                new ObjectParameter("iddm", iddm) :
                new ObjectParameter("iddm", typeof(string));
    
            var tendanhmucParameter = tendanhmuc != null ?
                new ObjectParameter("tendanhmuc", tendanhmuc) :
                new ObjectParameter("tendanhmuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaDanhMuc", iddmParameter, tendanhmucParameter);
        }
    
        public virtual int sp_ChinhSuaGiaBDG(string id, string idmonan, Nullable<double> giaApdung)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var idmonanParameter = idmonan != null ?
                new ObjectParameter("idmonan", idmonan) :
                new ObjectParameter("idmonan", typeof(string));
    
            var giaApdungParameter = giaApdung.HasValue ?
                new ObjectParameter("giaApdung", giaApdung) :
                new ObjectParameter("giaApdung", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaGiaBDG", idParameter, idmonanParameter, giaApdungParameter);
        }
    
        public virtual int sp_ChinhSuaLoaiKH(string idloaikh, string tenloaikh, Nullable<double> chietkhau)
        {
            var idloaikhParameter = idloaikh != null ?
                new ObjectParameter("idloaikh", idloaikh) :
                new ObjectParameter("idloaikh", typeof(string));
    
            var tenloaikhParameter = tenloaikh != null ?
                new ObjectParameter("tenloaikh", tenloaikh) :
                new ObjectParameter("tenloaikh", typeof(string));
    
            var chietkhauParameter = chietkhau.HasValue ?
                new ObjectParameter("chietkhau", chietkhau) :
                new ObjectParameter("chietkhau", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaLoaiKH", idloaikhParameter, tenloaikhParameter, chietkhauParameter);
        }
    
        public virtual int sp_ChinhSuaMA(string id, string tenma, string mota, Nullable<double> giagoc, string iddanhmuc, string idcongthuc, string hinhanh)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var tenmaParameter = tenma != null ?
                new ObjectParameter("tenma", tenma) :
                new ObjectParameter("tenma", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var giagocParameter = giagoc.HasValue ?
                new ObjectParameter("giagoc", giagoc) :
                new ObjectParameter("giagoc", typeof(double));
    
            var iddanhmucParameter = iddanhmuc != null ?
                new ObjectParameter("iddanhmuc", iddanhmuc) :
                new ObjectParameter("iddanhmuc", typeof(string));
    
            var idcongthucParameter = idcongthuc != null ?
                new ObjectParameter("idcongthuc", idcongthuc) :
                new ObjectParameter("idcongthuc", typeof(string));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("hinhanh", hinhanh) :
                new ObjectParameter("hinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaMA", idParameter, tenmaParameter, motaParameter, giagocParameter, iddanhmucParameter, idcongthucParameter, hinhanhParameter);
        }
    
        public virtual int sp_ChinhSuaMACN(string id, string idma, string locationid)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var idmaParameter = idma != null ?
                new ObjectParameter("idma", idma) :
                new ObjectParameter("idma", typeof(string));
    
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaMACN", idParameter, idmaParameter, locationidParameter);
        }
    
        public virtual int sp_ChinhSuaNL(string idnl, string tennl, Nullable<double> trongluong, string donvi, string tenncc, Nullable<int> baoquan, Nullable<System.DateTime> ngaysx, Nullable<System.DateTime> hansd)
        {
            var idnlParameter = idnl != null ?
                new ObjectParameter("idnl", idnl) :
                new ObjectParameter("idnl", typeof(string));
    
            var tennlParameter = tennl != null ?
                new ObjectParameter("tennl", tennl) :
                new ObjectParameter("tennl", typeof(string));
    
            var trongluongParameter = trongluong.HasValue ?
                new ObjectParameter("trongluong", trongluong) :
                new ObjectParameter("trongluong", typeof(double));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            var baoquanParameter = baoquan.HasValue ?
                new ObjectParameter("baoquan", baoquan) :
                new ObjectParameter("baoquan", typeof(int));
    
            var ngaysxParameter = ngaysx.HasValue ?
                new ObjectParameter("ngaysx", ngaysx) :
                new ObjectParameter("ngaysx", typeof(System.DateTime));
    
            var hansdParameter = hansd.HasValue ?
                new ObjectParameter("hansd", hansd) :
                new ObjectParameter("hansd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaNL", idnlParameter, tennlParameter, trongluongParameter, donviParameter, tennccParameter, baoquanParameter, ngaysxParameter, hansdParameter);
        }
    
        public virtual int sp_ChinhSuaPX(string id, string idkho, string idnv, string idnguyenlieu, Nullable<int> soluong)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var idkhoParameter = idkho != null ?
                new ObjectParameter("idkho", idkho) :
                new ObjectParameter("idkho", typeof(string));
    
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            var idnguyenlieuParameter = idnguyenlieu != null ?
                new ObjectParameter("idnguyenlieu", idnguyenlieu) :
                new ObjectParameter("idnguyenlieu", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaPX", idParameter, idkhoParameter, idnvParameter, idnguyenlieuParameter, soluongParameter);
        }
    
        public virtual int sp_ChinhSuaTT(string id, string tieude, string noidung, string hinhanh1, string hinhanh2, string hinhanh3, string locationId)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var tieudeParameter = tieude != null ?
                new ObjectParameter("tieude", tieude) :
                new ObjectParameter("tieude", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var hinhanh1Parameter = hinhanh1 != null ?
                new ObjectParameter("hinhanh1", hinhanh1) :
                new ObjectParameter("hinhanh1", typeof(string));
    
            var hinhanh2Parameter = hinhanh2 != null ?
                new ObjectParameter("hinhanh2", hinhanh2) :
                new ObjectParameter("hinhanh2", typeof(string));
    
            var hinhanh3Parameter = hinhanh3 != null ?
                new ObjectParameter("hinhanh3", hinhanh3) :
                new ObjectParameter("hinhanh3", typeof(string));
    
            var locationIdParameter = locationId != null ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaTT", idParameter, tieudeParameter, noidungParameter, hinhanh1Parameter, hinhanh2Parameter, hinhanh3Parameter, locationIdParameter);
        }
    
        public virtual int sp_ChinhSuaVoucher(string idvoucher, string tenvoucher, Nullable<System.DateTime> ngayapdung, Nullable<System.DateTime> ngayhethan, string mota, Nullable<double> discount, Nullable<bool> @lock)
        {
            var idvoucherParameter = idvoucher != null ?
                new ObjectParameter("idvoucher", idvoucher) :
                new ObjectParameter("idvoucher", typeof(string));
    
            var tenvoucherParameter = tenvoucher != null ?
                new ObjectParameter("tenvoucher", tenvoucher) :
                new ObjectParameter("tenvoucher", typeof(string));
    
            var ngayapdungParameter = ngayapdung.HasValue ?
                new ObjectParameter("ngayapdung", ngayapdung) :
                new ObjectParameter("ngayapdung", typeof(System.DateTime));
    
            var ngayhethanParameter = ngayhethan.HasValue ?
                new ObjectParameter("ngayhethan", ngayhethan) :
                new ObjectParameter("ngayhethan", typeof(System.DateTime));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("discount", discount) :
                new ObjectParameter("discount", typeof(double));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaVoucher", idvoucherParameter, tenvoucherParameter, ngayapdungParameter, ngayhethanParameter, motaParameter, discountParameter, lockParameter);
        }
    
        public virtual ObjectResult<sp_HienThiDanhSachVoucher_Result> sp_HienThiDanhSachVoucher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiDanhSachVoucher_Result>("sp_HienThiDanhSachVoucher");
        }
    
        public virtual int sp_LockBDG(string idbdg, string idma, Nullable<bool> @lock)
        {
            var idbdgParameter = idbdg != null ?
                new ObjectParameter("idbdg", idbdg) :
                new ObjectParameter("idbdg", typeof(string));
    
            var idmaParameter = idma != null ?
                new ObjectParameter("idma", idma) :
                new ObjectParameter("idma", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockBDG", idbdgParameter, idmaParameter, lockParameter);
        }
    
        public virtual int sp_LockCN(string idcn, Nullable<bool> @lock)
        {
            var idcnParameter = idcn != null ?
                new ObjectParameter("idcn", idcn) :
                new ObjectParameter("idcn", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockCN", idcnParameter, lockParameter);
        }
    
        public virtual int sp_LockCT(string idct, Nullable<bool> @lock)
        {
            var idctParameter = idct != null ?
                new ObjectParameter("idct", idct) :
                new ObjectParameter("idct", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockCT", idctParameter, lockParameter);
        }
    
        public virtual int sp_LockCTCT(string idctnl, Nullable<bool> @lock)
        {
            var idctnlParameter = idctnl != null ?
                new ObjectParameter("idctnl", idctnl) :
                new ObjectParameter("idctnl", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockCTCT", idctnlParameter, lockParameter);
        }
    
        public virtual int sp_LockDM(string iddm, Nullable<bool> @lock)
        {
            var iddmParameter = iddm != null ?
                new ObjectParameter("iddm", iddm) :
                new ObjectParameter("iddm", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockDM", iddmParameter, lockParameter);
        }
    
        public virtual int sp_LockFeedback(string idfb)
        {
            var idfbParameter = idfb != null ?
                new ObjectParameter("idfb", idfb) :
                new ObjectParameter("idfb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockFeedback", idfbParameter);
        }
    
        public virtual int sp_LockKH(string idkh)
        {
            var idkhParameter = idkh != null ?
                new ObjectParameter("idkh", idkh) :
                new ObjectParameter("idkh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockKH", idkhParameter);
        }
    
        public virtual int sp_LockLoaiKH(string idloaikh)
        {
            var idloaikhParameter = idloaikh != null ?
                new ObjectParameter("idloaikh", idloaikh) :
                new ObjectParameter("idloaikh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockLoaiKH", idloaikhParameter);
        }
    
        public virtual int sp_LockMA(string idma, Nullable<bool> @lock)
        {
            var idmaParameter = idma != null ?
                new ObjectParameter("idma", idma) :
                new ObjectParameter("idma", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockMA", idmaParameter, lockParameter);
        }
    
        public virtual int sp_LockMACN(string id, Nullable<bool> @lock)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockMACN", idParameter, lockParameter);
        }
    
        public virtual int sp_LockNL(string idnl, Nullable<bool> @lock)
        {
            var idnlParameter = idnl != null ?
                new ObjectParameter("idnl", idnl) :
                new ObjectParameter("idnl", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockNL", idnlParameter, lockParameter);
        }
    
        public virtual int sp_LockPNX(string idpn, Nullable<bool> @lock)
        {
            var idpnParameter = idpn != null ?
                new ObjectParameter("idpn", idpn) :
                new ObjectParameter("idpn", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockPNX", idpnParameter, lockParameter);
        }
    
        public virtual int sp_LockPX(string idpx, Nullable<bool> @lock)
        {
            var idpxParameter = idpx != null ?
                new ObjectParameter("idpx", idpx) :
                new ObjectParameter("idpx", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockPX", idpxParameter, lockParameter);
        }
    
        public virtual int sp_LockTT(string idtt, Nullable<bool> @lock)
        {
            var idttParameter = idtt != null ?
                new ObjectParameter("idtt", idtt) :
                new ObjectParameter("idtt", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockTT", idttParameter, lockParameter);
        }
    
        public virtual int sp_LockVoucher(string idvoucher)
        {
            var idvoucherParameter = idvoucher != null ?
                new ObjectParameter("idvoucher", idvoucher) :
                new ObjectParameter("idvoucher", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockVoucher", idvoucherParameter);
        }
    
        public virtual int sp_SuaFeedback(string feedbackID, Nullable<int> danhGia, string noiDung)
        {
            var feedbackIDParameter = feedbackID != null ?
                new ObjectParameter("FeedbackID", feedbackID) :
                new ObjectParameter("FeedbackID", typeof(string));
    
            var danhGiaParameter = danhGia.HasValue ?
                new ObjectParameter("DanhGia", danhGia) :
                new ObjectParameter("DanhGia", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaFeedback", feedbackIDParameter, danhGiaParameter, noiDungParameter);
        }
    
        public virtual int sp_SuaThongTinKH(string maKH, string password, string tenKH, string sDT, string diaChi, string email, string hinhAnh, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, string iDLoaiKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var iDLoaiKHParameter = iDLoaiKH != null ?
                new ObjectParameter("IDLoaiKH", iDLoaiKH) :
                new ObjectParameter("IDLoaiKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaThongTinKH", maKHParameter, passwordParameter, tenKHParameter, sDTParameter, diaChiParameter, emailParameter, hinhAnhParameter, ngaySinhParameter, gioiTinhParameter, iDLoaiKHParameter);
        }
    
        public virtual int sp_ThemBDG(string idmonan, Nullable<double> giaapdung, Nullable<System.DateTime> ngayapdung, Nullable<System.DateTime> ngayhethan)
        {
            var idmonanParameter = idmonan != null ?
                new ObjectParameter("idmonan", idmonan) :
                new ObjectParameter("idmonan", typeof(string));
    
            var giaapdungParameter = giaapdung.HasValue ?
                new ObjectParameter("giaapdung", giaapdung) :
                new ObjectParameter("giaapdung", typeof(double));
    
            var ngayapdungParameter = ngayapdung.HasValue ?
                new ObjectParameter("ngayapdung", ngayapdung) :
                new ObjectParameter("ngayapdung", typeof(System.DateTime));
    
            var ngayhethanParameter = ngayhethan.HasValue ?
                new ObjectParameter("ngayhethan", ngayhethan) :
                new ObjectParameter("ngayhethan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemBDG", idmonanParameter, giaapdungParameter, ngayapdungParameter, ngayhethanParameter);
        }
    
        public virtual int sp_ThemCN(string tencn, string diachi, string nvql)
        {
            var tencnParameter = tencn != null ?
                new ObjectParameter("tencn", tencn) :
                new ObjectParameter("tencn", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var nvqlParameter = nvql != null ?
                new ObjectParameter("nvql", nvql) :
                new ObjectParameter("nvql", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCN", tencnParameter, diachiParameter, nvqlParameter);
        }
    
        public virtual int sp_ThemCT(string tenct, string mota)
        {
            var tenctParameter = tenct != null ?
                new ObjectParameter("tenct", tenct) :
                new ObjectParameter("tenct", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCT", tenctParameter, motaParameter);
        }
    
        public virtual int sp_ThemCTCT(string idnguyenlieu, string idcongthuc, Nullable<int> soluong)
        {
            var idnguyenlieuParameter = idnguyenlieu != null ?
                new ObjectParameter("idnguyenlieu", idnguyenlieu) :
                new ObjectParameter("idnguyenlieu", typeof(string));
    
            var idcongthucParameter = idcongthuc != null ?
                new ObjectParameter("idcongthuc", idcongthuc) :
                new ObjectParameter("idcongthuc", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCTCT", idnguyenlieuParameter, idcongthucParameter, soluongParameter);
        }
    
        public virtual int sp_ThemCTPNX(string idpn, string idnguyenlieu, Nullable<int> soluong)
        {
            var idpnParameter = idpn != null ?
                new ObjectParameter("idpn", idpn) :
                new ObjectParameter("idpn", typeof(string));
    
            var idnguyenlieuParameter = idnguyenlieu != null ?
                new ObjectParameter("idnguyenlieu", idnguyenlieu) :
                new ObjectParameter("idnguyenlieu", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCTPNX", idpnParameter, idnguyenlieuParameter, soluongParameter);
        }
    
        public virtual int sp_ThemDanhMuc(string tendanhmuc)
        {
            var tendanhmucParameter = tendanhmuc != null ?
                new ObjectParameter("tendanhmuc", tendanhmuc) :
                new ObjectParameter("tendanhmuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDanhMuc", tendanhmucParameter);
        }
    
        public virtual int sp_ThemFeedback(Nullable<System.DateTime> ngayTao, Nullable<int> danhGia, string noiDung, string iDHoaDon, Nullable<bool> @lock)
        {
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            var danhGiaParameter = danhGia.HasValue ?
                new ObjectParameter("DanhGia", danhGia) :
                new ObjectParameter("DanhGia", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var iDHoaDonParameter = iDHoaDon != null ?
                new ObjectParameter("IDHoaDon", iDHoaDon) :
                new ObjectParameter("IDHoaDon", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("Lock", @lock) :
                new ObjectParameter("Lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemFeedback", ngayTaoParameter, danhGiaParameter, noiDungParameter, iDHoaDonParameter, lockParameter);
        }
    
        public virtual int sp_ThemHD(Nullable<bool> trangThai, Nullable<double> tongCong, string iDVoucher, string maNVLap, string maKH, string locationid, ObjectParameter maHoaDonTrongOutput)
        {
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var tongCongParameter = tongCong.HasValue ?
                new ObjectParameter("TongCong", tongCong) :
                new ObjectParameter("TongCong", typeof(double));
    
            var iDVoucherParameter = iDVoucher != null ?
                new ObjectParameter("IDVoucher", iDVoucher) :
                new ObjectParameter("IDVoucher", typeof(string));
    
            var maNVLapParameter = maNVLap != null ?
                new ObjectParameter("MaNVLap", maNVLap) :
                new ObjectParameter("MaNVLap", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var locationidParameter = locationid != null ?
                new ObjectParameter("Locationid", locationid) :
                new ObjectParameter("Locationid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemHD", trangThaiParameter, tongCongParameter, iDVoucherParameter, maNVLapParameter, maKHParameter, locationidParameter, maHoaDonTrongOutput);
        }
    
        public virtual int sp_ThemKH(string userName, string password, string tenKH, string sDT, string diaChi, string email, string hinhAnh, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, string iDLoaiKH, Nullable<bool> @lock)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var iDLoaiKHParameter = iDLoaiKH != null ?
                new ObjectParameter("IDLoaiKH", iDLoaiKH) :
                new ObjectParameter("IDLoaiKH", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("Lock", @lock) :
                new ObjectParameter("Lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKH", userNameParameter, passwordParameter, tenKHParameter, sDTParameter, diaChiParameter, emailParameter, hinhAnhParameter, ngaySinhParameter, gioiTinhParameter, iDLoaiKHParameter, lockParameter);
        }
    
        public virtual int sp_ThemLoaiKH(string tenloai, Nullable<double> chietkhau, Nullable<bool> @lock)
        {
            var tenloaiParameter = tenloai != null ?
                new ObjectParameter("tenloai", tenloai) :
                new ObjectParameter("tenloai", typeof(string));
    
            var chietkhauParameter = chietkhau.HasValue ?
                new ObjectParameter("chietkhau", chietkhau) :
                new ObjectParameter("chietkhau", typeof(double));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLoaiKH", tenloaiParameter, chietkhauParameter, lockParameter);
        }
    
        public virtual int sp_ThemMA(string tenmonan, string mota, Nullable<double> giagoc, string iddanhmuc, string idcongthuc, string hinhanh)
        {
            var tenmonanParameter = tenmonan != null ?
                new ObjectParameter("tenmonan", tenmonan) :
                new ObjectParameter("tenmonan", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var giagocParameter = giagoc.HasValue ?
                new ObjectParameter("giagoc", giagoc) :
                new ObjectParameter("giagoc", typeof(double));
    
            var iddanhmucParameter = iddanhmuc != null ?
                new ObjectParameter("iddanhmuc", iddanhmuc) :
                new ObjectParameter("iddanhmuc", typeof(string));
    
            var idcongthucParameter = idcongthuc != null ?
                new ObjectParameter("idcongthuc", idcongthuc) :
                new ObjectParameter("idcongthuc", typeof(string));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("hinhanh", hinhanh) :
                new ObjectParameter("hinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMA", tenmonanParameter, motaParameter, giagocParameter, iddanhmucParameter, idcongthucParameter, hinhanhParameter);
        }
    
        public virtual int sp_ThemMACN(string idma, string locationid, string manv)
        {
            var idmaParameter = idma != null ?
                new ObjectParameter("idma", idma) :
                new ObjectParameter("idma", typeof(string));
    
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMACN", idmaParameter, locationidParameter, manvParameter);
        }
    
        public virtual int sp_ThemNL(string tennl, Nullable<double> soluong, string donvi, string tenncc, Nullable<int> baoquan, Nullable<System.DateTime> ngaysx, Nullable<System.DateTime> hansd)
        {
            var tennlParameter = tennl != null ?
                new ObjectParameter("tennl", tennl) :
                new ObjectParameter("tennl", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(double));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            var baoquanParameter = baoquan.HasValue ?
                new ObjectParameter("baoquan", baoquan) :
                new ObjectParameter("baoquan", typeof(int));
    
            var ngaysxParameter = ngaysx.HasValue ?
                new ObjectParameter("ngaysx", ngaysx) :
                new ObjectParameter("ngaysx", typeof(System.DateTime));
    
            var hansdParameter = hansd.HasValue ?
                new ObjectParameter("hansd", hansd) :
                new ObjectParameter("hansd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNL", tennlParameter, soluongParameter, donviParameter, tennccParameter, baoquanParameter, ngaysxParameter, hansdParameter);
        }
    
        public virtual int sp_ThemPNX(string idkho, string idnv, Nullable<bool> loaiphieu, Nullable<System.DateTime> ngaylap, ObjectParameter maphieu)
        {
            var idkhoParameter = idkho != null ?
                new ObjectParameter("idkho", idkho) :
                new ObjectParameter("idkho", typeof(string));
    
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            var loaiphieuParameter = loaiphieu.HasValue ?
                new ObjectParameter("loaiphieu", loaiphieu) :
                new ObjectParameter("loaiphieu", typeof(bool));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPNX", idkhoParameter, idnvParameter, loaiphieuParameter, ngaylapParameter, maphieu);
        }
    
        public virtual int sp_ThemPX(string idkho, string idnv, Nullable<System.DateTime> ngaylap, string idnguyenlieu, Nullable<int> soluong)
        {
            var idkhoParameter = idkho != null ?
                new ObjectParameter("idkho", idkho) :
                new ObjectParameter("idkho", typeof(string));
    
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            var idnguyenlieuParameter = idnguyenlieu != null ?
                new ObjectParameter("idnguyenlieu", idnguyenlieu) :
                new ObjectParameter("idnguyenlieu", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPX", idkhoParameter, idnvParameter, ngaylapParameter, idnguyenlieuParameter, soluongParameter);
        }
    
        public virtual int sp_ThemTT(string tieude, string noidung, string hinhanh1, string hinhanh2, string hinhanh3, string locationId, string manv, Nullable<System.DateTime> ngaydang)
        {
            var tieudeParameter = tieude != null ?
                new ObjectParameter("tieude", tieude) :
                new ObjectParameter("tieude", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var hinhanh1Parameter = hinhanh1 != null ?
                new ObjectParameter("hinhanh1", hinhanh1) :
                new ObjectParameter("hinhanh1", typeof(string));
    
            var hinhanh2Parameter = hinhanh2 != null ?
                new ObjectParameter("hinhanh2", hinhanh2) :
                new ObjectParameter("hinhanh2", typeof(string));
    
            var hinhanh3Parameter = hinhanh3 != null ?
                new ObjectParameter("hinhanh3", hinhanh3) :
                new ObjectParameter("hinhanh3", typeof(string));
    
            var locationIdParameter = locationId != null ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var ngaydangParameter = ngaydang.HasValue ?
                new ObjectParameter("ngaydang", ngaydang) :
                new ObjectParameter("ngaydang", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemTT", tieudeParameter, noidungParameter, hinhanh1Parameter, hinhanh2Parameter, hinhanh3Parameter, locationIdParameter, manvParameter, ngaydangParameter);
        }
    
        public virtual int sp_ThemVoucher(string tenvoucher, Nullable<System.DateTime> ngayapdung, Nullable<System.DateTime> ngayhethan, string mota, Nullable<double> discount, string locationid, Nullable<bool> @lock, string manv)
        {
            var tenvoucherParameter = tenvoucher != null ?
                new ObjectParameter("tenvoucher", tenvoucher) :
                new ObjectParameter("tenvoucher", typeof(string));
    
            var ngayapdungParameter = ngayapdung.HasValue ?
                new ObjectParameter("ngayapdung", ngayapdung) :
                new ObjectParameter("ngayapdung", typeof(System.DateTime));
    
            var ngayhethanParameter = ngayhethan.HasValue ?
                new ObjectParameter("ngayhethan", ngayhethan) :
                new ObjectParameter("ngayhethan", typeof(System.DateTime));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("discount", discount) :
                new ObjectParameter("discount", typeof(double));
    
            var locationidParameter = locationid != null ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemVoucher", tenvoucherParameter, ngayapdungParameter, ngayhethanParameter, motaParameter, discountParameter, locationidParameter, lockParameter, manvParameter);
        }
    
        public virtual int sp_XoaBDG(string id, string idmonan)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var idmonanParameter = idmonan != null ?
                new ObjectParameter("idmonan", idmonan) :
                new ObjectParameter("idmonan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaBDG", idParameter, idmonanParameter);
        }
    
        public virtual int sp_XoaCN(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaCN", idParameter);
        }
    
        public virtual int sp_XoaCT(string idct)
        {
            var idctParameter = idct != null ?
                new ObjectParameter("idct", idct) :
                new ObjectParameter("idct", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaCT", idctParameter);
        }
    
        public virtual int sp_XoaCTCT(string id, string idcongthuc)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var idcongthucParameter = idcongthuc != null ?
                new ObjectParameter("idcongthuc", idcongthuc) :
                new ObjectParameter("idcongthuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaCTCT", idParameter, idcongthucParameter);
        }
    
        public virtual int sp_XoaDanhMuc(string iddm)
        {
            var iddmParameter = iddm != null ?
                new ObjectParameter("iddm", iddm) :
                new ObjectParameter("iddm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaDanhMuc", iddmParameter);
        }
    
        public virtual int sp_XoaFeedback(string idfb)
        {
            var idfbParameter = idfb != null ?
                new ObjectParameter("idfb", idfb) :
                new ObjectParameter("idfb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaFeedback", idfbParameter);
        }
    
        public virtual int sp_XoaKH(string idkh)
        {
            var idkhParameter = idkh != null ?
                new ObjectParameter("idkh", idkh) :
                new ObjectParameter("idkh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKH", idkhParameter);
        }
    
        public virtual int sp_XoaLoaiKH(string idloaikh)
        {
            var idloaikhParameter = idloaikh != null ?
                new ObjectParameter("idloaikh", idloaikh) :
                new ObjectParameter("idloaikh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaLoaiKH", idloaikhParameter);
        }
    
        public virtual int sp_XoaMA(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaMA", idParameter);
        }
    
        public virtual int sp_XoaMACN(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaMACN", idParameter);
        }
    
        public virtual int sp_XoaNL(string idnl)
        {
            var idnlParameter = idnl != null ?
                new ObjectParameter("idnl", idnl) :
                new ObjectParameter("idnl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNL", idnlParameter);
        }
    
        public virtual int sp_XoaPNX(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaPNX", idParameter);
        }
    
        public virtual int sp_XoaPX(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaPX", idParameter);
        }
    
        public virtual int sp_XoaTT(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaTT", idParameter);
        }
    
        public virtual int sp_XoaVoucher(string idvoucher)
        {
            var idvoucherParameter = idvoucher != null ?
                new ObjectParameter("idvoucher", idvoucher) :
                new ObjectParameter("idvoucher", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaVoucher", idvoucherParameter);
        }
    
        public virtual int sp_ThemChiTietHD(string iDHoaDon, string iDMonAn, Nullable<int> soLuong, Nullable<double> giaBan)
        {
            var iDHoaDonParameter = iDHoaDon != null ?
                new ObjectParameter("IDHoaDon", iDHoaDon) :
                new ObjectParameter("IDHoaDon", typeof(string));
    
            var iDMonAnParameter = iDMonAn != null ?
                new ObjectParameter("IDMonAn", iDMonAn) :
                new ObjectParameter("IDMonAn", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChiTietHD", iDHoaDonParameter, iDMonAnParameter, soLuongParameter, giaBanParameter);
        }
    
        public virtual int sp_XoaHD(string idhd)
        {
            var idhdParameter = idhd != null ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaHD", idhdParameter);
        }
    
        public virtual int sp_CheckTonKho(string iDHoaDon, string locationID)
        {
            var iDHoaDonParameter = iDHoaDon != null ?
                new ObjectParameter("IDHoaDon", iDHoaDon) :
                new ObjectParameter("IDHoaDon", typeof(string));
    
            var locationIDParameter = locationID != null ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CheckTonKho", iDHoaDonParameter, locationIDParameter);
        }
    
        public virtual int sp_LockHD(string idhd)
        {
            var idhdParameter = idhd != null ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockHD", idhdParameter);
        }
    
        public virtual int sp_ChinhSuaCV(string maCV, string tenCV, string viTri)
        {
            var maCVParameter = maCV != null ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(string));
    
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("TenCV", tenCV) :
                new ObjectParameter("TenCV", typeof(string));
    
            var viTriParameter = viTri != null ?
                new ObjectParameter("ViTri", viTri) :
                new ObjectParameter("ViTri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChinhSuaCV", maCVParameter, tenCVParameter, viTriParameter);
        }
    
        public virtual int sp_LockCV(string idcv)
        {
            var idcvParameter = idcv != null ?
                new ObjectParameter("idcv", idcv) :
                new ObjectParameter("idcv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockCV", idcvParameter);
        }
    
        public virtual int sp_XoaCV(string idcv)
        {
            var idcvParameter = idcv != null ?
                new ObjectParameter("idcv", idcv) :
                new ObjectParameter("idcv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaCV", idcvParameter);
        }
    
        public virtual int sp_XoaNV(string idnv)
        {
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNV", idnvParameter);
        }
    
        public virtual int sp_LockNV(string idnv)
        {
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LockNV", idnvParameter);
        }
    
        public virtual int sp_SuaThongTinNV(string maNV, string password, string tenNV, string sDT, string diaChi, string email, string hinhAnh, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, string maCV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var maCVParameter = maCV != null ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaThongTinNV", maNVParameter, passwordParameter, tenNVParameter, sDTParameter, diaChiParameter, emailParameter, hinhAnhParameter, ngaySinhParameter, gioiTinhParameter, maCVParameter);
        }
    
        public virtual int sp_ThemCV(string maCV, string tenCV, string viTri, Nullable<bool> @lock)
        {
            var maCVParameter = maCV != null ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(string));
    
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("TenCV", tenCV) :
                new ObjectParameter("TenCV", typeof(string));
    
            var viTriParameter = viTri != null ?
                new ObjectParameter("ViTri", viTri) :
                new ObjectParameter("ViTri", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("Lock", @lock) :
                new ObjectParameter("Lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCV", maCVParameter, tenCVParameter, viTriParameter, lockParameter);
        }
    
        public virtual int sp_ThemNV(string maNV, string userName, string password, string tenNV, string sDT, string diaChi, string email, string hinhAnh, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, string maCV, Nullable<bool> @lock)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var maCVParameter = maCV != null ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("Lock", @lock) :
                new ObjectParameter("Lock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNV", maNVParameter, userNameParameter, passwordParameter, tenNVParameter, sDTParameter, diaChiParameter, emailParameter, hinhAnhParameter, ngaySinhParameter, gioiTinhParameter, maCVParameter, lockParameter);
        }
    
        public virtual int sp_XetDuyetHD(string mahd, Nullable<bool> trangthai)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XetDuyetHD", mahdParameter, trangthaiParameter);
        }
    
        public virtual int sp_CapNhatAvartarKH(string idkh, string hinhanh)
        {
            var idkhParameter = idkh != null ?
                new ObjectParameter("idkh", idkh) :
                new ObjectParameter("idkh", typeof(string));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("hinhanh", hinhanh) :
                new ObjectParameter("hinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatAvartarKH", idkhParameter, hinhanhParameter);
        }
    
        public virtual int sp_CapNhatMKKH(string idkh, string pass)
        {
            var idkhParameter = idkh != null ?
                new ObjectParameter("idkh", idkh) :
                new ObjectParameter("idkh", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatMKKH", idkhParameter, passParameter);
        }
    
        public virtual int sp_CapNhatTTKH(string idkh, string tenkh, string sdt, string diachi, string email, Nullable<System.DateTime> ngaysinh, string cccd)
        {
            var idkhParameter = idkh != null ?
                new ObjectParameter("idkh", idkh) :
                new ObjectParameter("idkh", typeof(string));
    
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var cccdParameter = cccd != null ?
                new ObjectParameter("cccd", cccd) :
                new ObjectParameter("cccd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTTKH", idkhParameter, tenkhParameter, sdtParameter, diachiParameter, emailParameter, ngaysinhParameter, cccdParameter);
        }
    
        public virtual int sp_XetDuyetMACN(string id, Nullable<int> trangthai)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XetDuyetMACN", idParameter, trangthaiParameter);
        }
    
        public virtual int sp_XetDuyetVoucher(string id, Nullable<int> trangthai)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XetDuyetVoucher", idParameter, trangthaiParameter);
        }
    
        public virtual ObjectResult<sp_HienThiDSYT_Result> sp_HienThiDSYT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiDSYT_Result>("sp_HienThiDSYT");
        }
    
        public virtual int sp_ThemDSYT(string maKH, string iDMonAn, string locationID)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var iDMonAnParameter = iDMonAn != null ?
                new ObjectParameter("IDMonAn", iDMonAn) :
                new ObjectParameter("IDMonAn", typeof(string));
    
            var locationIDParameter = locationID != null ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDSYT", maKHParameter, iDMonAnParameter, locationIDParameter);
        }
    
        public virtual int sp_XoaDSYT(string maKH, string iDMonAn, string locationID)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var iDMonAnParameter = iDMonAn != null ?
                new ObjectParameter("IDMonAn", iDMonAn) :
                new ObjectParameter("IDMonAn", typeof(string));
    
            var locationIDParameter = locationID != null ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaDSYT", maKHParameter, iDMonAnParameter, locationIDParameter);
        }
    }
}
