//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodBranch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenLieu()
        {
            this.ChiTietCTs = new HashSet<ChiTietCT>();
            this.ChiTietKhoes = new HashSet<ChiTietKho>();
            this.ChiTietPNXes = new HashSet<ChiTietPNX>();
        }
    
        public string ID { get; set; }
        public string TenNL { get; set; }
        public string DonVi { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<double> TrongLuong { get; set; }
        public string TenNCC { get; set; }
        public Nullable<int> BaoQuan { get; set; }
        public Nullable<System.DateTime> NgaySX { get; set; }
        public Nullable<System.DateTime> HanSD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietCT> ChiTietCTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKho> ChiTietKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPNX> ChiTietPNXes { get; set; }
    }
}
